Implement Bookmarks
superseriousbusiness/gotosocial pull request #1168
Opened 2022-11-29 01:01 UTC by matthewp

Fixes https://github.com/superseriousbusiness/gotosocial/issues/1112

This is my first contribution to GoToSocial, let me know if I did anything wrong. And thanks!

2022-11-29 13:02 UTC, matthewp commented
I'm not sure why the tests are failing. I think perhaps I'm not cleaning up some resources or something... if someone has some hints please let me know.

2022-11-29 14:49 UTC, tsmethurst commented
> I'm not sure why the tests are failing

Was just a flakey test, I ran it again and it passes now :)

Thanks for the PR, will review soon(tm)

2022-12-01 14:07 UTC, tsmethurst requested changes
Thanks for this. This is coming along but not quite there yet, see comments.

You also need to update the swagger documentation for this, since you're adding endpoints; see the contributing.md for how to do this.

2022-12-01 14:07 UTC, tsmethurst commented on internal/processing/account/getbookmarks.go
> +	var filtered []*gtsmodel.Status
replace with `filtered := make([]*gtsmodel.Status, 0, len(statuses)`

2022-12-01 14:07 UTC, tsmethurst commented on internal/processing/status/bookmark.go
> +func (p *processor) Bookmark(ctx context.Context, requestingAccount *gtsmodel.Account, application *gtsmodel.Application, targetStatusID string) (*apimodel.Status, gtserror.WithCode) {
i don't think the application is used for anything here is it?

2022-12-01 14:07 UTC, tsmethurst commented on internal/processing/status/unbookmark.go
> +	// TODO the real logic
?

2022-12-07 02:28 UTC, matthewp commented
Figured out the swagger doc and updated that. This is ready for another review.

2022-12-07 20:33 UTC, tsmethurst commented
> This is ready for another review

Are you sure? It looks like it's not compiling or passing tests yet :P

2022-12-07 20:53 UTC, matthewp commented
@tsmethurst Ah my bad, I thought the failing CI was a flakey test like last time. I'll take a look, I probably missed updating a function name or something.

2022-12-07 20:56 UTC, tsmethurst commented
No problem. It's a good idea to just run tests locally yourself every time before you push, just to make sure.

2022-12-07 21:28 UTC, matthewp commented
@tsmethurst Tests are passing now.

2022-12-07 21:30 UTC, tsmethurst commented
Great stuff, thank you! I will review again in the morning :)

2022-12-08 13:34 UTC, tsmethurst requested changes
Looking a lot better :) Few things left to check/change though! Thank you for your work so far!

2022-12-08 13:34 UTC, tsmethurst commented on docs/api/swagger.yaml
> +                            $ref: '#/definitions/bookmark'
ah right, i misunderstood something before; so the bookmarks endpoints returns an array of statuses right?

so my previous comment was wrong, and this ref needs to be changed to `'#/definitions/status'`, i believe

2022-12-08 13:34 UTC, tsmethurst commented on internal/api/client/bookmarks/bookmarks_test.go
> +	//statusReply := &model.Status{}
delete unused line

2022-12-08 13:34 UTC, tsmethurst commented on internal/db/bundb/account.go
> +		q = q.Where("? = ?", bun.Ident("status_bookmark.account_id"), accountID)
accountID should always be set, right? since bookmarks are made per account, and there's no reason to get a list of all bookmarks; perhaps it's worth erroring instead of accountID == ""

2022-12-08 13:34 UTC, tsmethurst commented on internal/processing/account/getbookmarks.go
> +		NextMaxIDValue:   nextMaxIDValue,
The way this code currently is, the next and previous id values are derived from the first and last statuses in the slice, but this logic is actually incorrect: it should be derived from the first and last *bookmark IDs*. I believe you can use the maxID and minID parameters passed into this function to do this instead.

2022-12-08 13:34 UTC, tsmethurst commented on internal/processing/status/bookmark.go
> +
we should check here to make sure the bookmarked status is actually visible to the requester, otherwise someone could eg., submit a bookmark to a status they're not allowed to view, and then when they request their bookmarks, they'd be able to see the status

2022-12-08 13:34 UTC, tsmethurst commented on internal/processing/status/unbookmark.go
> +
same comment as above: check if they're allowed to view the status before processing

2022-12-08 21:24 UTC, matthewp commented on internal/processing/account/getbookmarks.go
> +		NextMaxIDValue:   nextMaxIDValue,
Think I got this working.

2022-12-08 21:39 UTC, matthewp commented
@tsmethurst ready for another review when you get a chance. Changes are all in dbf42c105f2ca9bb52be0860fb731e1c5bf27bf0

2022-12-09 10:36 UTC, tsmethurst commented
Looks good now, so I will merge it! Thank you for your hard work, and for making all the changes :) Very much appreciated, looking forward to trying this out

2022-12-09 10:37 UTC, merged