AWS S3 config details added
superseriousbusiness/gotosocial pull request #1300
Opened 2023-01-04 12:16 UTC by anantshri

# Description

It was interesting to note that since presigned urls are used buckets dont need to be exposed publically. this was an interesting change compared to other mastodon specific s3 bucket guides hence documented here for correct directions.

## Checklist

- [x] I/we have read the [GoToSocial contribution guidelines](https://github.com/superseriousbusiness/gotosocial/blob/main/CONTRIBUTING.md).
- [x] I/we have discussed the proposed changes already, either in an issue on the repository, or in the Matrix chat.

2023-01-04 12:38 UTC, tsmethurst commented
This looks useful, but it's also rather AWS-centric, whereas S3 is not a protocol specific to AWS, but is also implemented by (eg) Minio, Wasabi, and others. I think it might be better to make these steps more general and less AWS specific.

Also, a sentence explaining the 'push existing data' section would be useful: this only applies if you're moving to s3 from local storage, not if you're setting up GtS for the first time, right?

2023-01-04 12:46 UTC, anantshri commented
Hey @tsmethurst makes sense. However I dont have experiance with other S3 environments. this is based on reading other guides doing misconfig then realizing this is far more straightforward then i expected.

I have added markers to make it clear this is AWS S3 specific. May be others can later add details around other implementations.

Reference guides that went all different directions. 
1. https://thomas-leister.de/en/mastodon-s3-media-storage/
2. https://github.com/cybrespace/cybrespace-meta/blob/master/s3.md

2023-01-04 15:03 UTC, igalic requested changes
here's some suggestions

2023-01-04 15:03 UTC, igalic commented on docs/configuration/storage.md
> +3. You can enable s3full access in case you dont want to care about security but recommendation would be to setup a tight permissions
or maybe we don't mention how to shoot yourself / your users in the foot?

or actively discourage it?

either way, the don't needs a '

2023-01-04 15:03 UTC, igalic commented on docs/configuration/storage.md
> +P.S. We gave ListAll for s3cmd to work nicely.
what does that mean?

2023-01-04 15:03 UTC, igalic commented on docs/configuration/storage.md
> +#### For Data migration from local storage to AWS s3 bucket in case of running instance. (not required if you are starting fresh)
this is too long to be a useful header

put the stuff () in a new paragraph, without the (), and a full sentence

2023-01-05 11:47 UTC, tsmethurst commented
Thanks @igalic ! 

@anantshri once you've resolved @igalic's suggestions I'm happy to merge this :)

2023-01-05 12:09 UTC, anantshri commented on docs/configuration/storage.md
> +replace <bucketname> in this sample policy
good spot merging this with above line remvoing s3full access part of sentence.

2023-01-05 12:09 UTC, anantshri commented on docs/configuration/storage.md
> +```
ah i keep forgetting that. adding.

2023-01-05 12:10 UTC, anantshri commented on docs/configuration/storage.md
> +3. You can enable s3full access in case you dont want to care about security but recommendation would be to setup a tight permissions
valuid point.

2023-01-05 12:11 UTC, anantshri commented on docs/configuration/storage.md
> +#### For Data migration from local storage to AWS s3 bucket in case of running instance. (not required if you are starting fresh)
Valid point rephrasing.

2023-01-05 12:16 UTC, anantshri commented
Updated @igalic please review when you can.

2023-01-05 13:05 UTC, igalic approved these changes
👍

2023-01-06 13:32 UTC, tsmethurst commented
Thanks! :)

2023-01-06 13:32 UTC, merged