Mention fixup
superseriousbusiness/gotosocial pull request #167
Opened 2021-08-28 10:09 UTC by tsmethurst

This PR fixes the issue of mentions not being created/notified correctly.

It also generally tidies up the dereferencing logic for statuses, and adds a couple of unit tests for said logic, so we can catch bugs more easily.

2021-08-28 11:12 UTC, NyaaaWhatsUpDoc requested changes

2021-08-28 11:12 UTC, NyaaaWhatsUpDoc commented on internal/federation/dereferencing/status.go
> +		if replyToStatus == nil {
Also should the status be coming back nil here when the err is nil too? I'm just a little worried we might be masking mysterious errors caused by nil statuses returned. If we let it panic then its a clear indication that something is wrong and needs attending to.

2021-08-28 11:12 UTC, NyaaaWhatsUpDoc commented on internal/typeutils/astointernal.go
> +		l.Infof("ASStatusToStatus: error extracting status URL: %s", err)
More a question here than definitive review -- is it worth returning errors here on failing to extract data? Or does that not necessarily indicate a broken status?

2021-08-28 11:12 UTC, NyaaaWhatsUpDoc commented on internal/typeutils/internaltofrontend.go
>  func (c *converter) StatusToMasto(ctx context.Context, s *gtsmodel.Status, requestingAccount *gtsmodel.Account) (*model.Status, error) {
Is there a reason we're logging instead of returning errors here now?

2021-08-28 11:12 UTC, NyaaaWhatsUpDoc commented
Apologies for the long-ass review :')

2021-08-28 11:15 UTC, tsmethurst commented on internal/util/regexes.go
> +	mentionNameRegexString = `^@(\w+)(?:@([a-zA-Z0-9_\-\.:]+)?)$`
yeah, it's for testing purposes specifically where the testrig instance has an explicit port in it, ie `localhost:8080`

2021-08-28 11:31 UTC, tsmethurst commented on internal/ap/extract.go
> +			return nil, errors.New("mention was not convertable to ap.Mentionable")
If the type is Mention we can assume it's `Mentionable`; if it's not then it's not valid activitystreams i believe, or at least not something we can process

2021-08-28 11:32 UTC, tsmethurst commented on internal/db/bundb/instance.go
> +		q = q.WhereGroup(" AND ", whereEmptyOrNull("domain"))
To simplify the query you mean? Or for some other reason?

2021-08-28 11:36 UTC, tsmethurst commented on internal/typeutils/astointernal.go
> +		l.Infof("ASStatusToStatus: error extracting status URL: %s", err)
Well, there's some things we absolutely need in order to consider a status as valid/displayable, but some stuff we don't and it's just nice extras. I just added the logging here so we can see what we're actually missing.

2021-08-28 11:36 UTC, tsmethurst commented on internal/typeutils/internaltofrontend.go
>  func (c *converter) StatusToMasto(ctx context.Context, s *gtsmodel.Status, requestingAccount *gtsmodel.Account) (*model.Status, error) {
See above: errors aren't necessarily a show-stopper, we might still be able to show a status even if all the fields aren't lined up properly,

2021-08-28 11:37 UTC, NyaaaWhatsUpDoc commented on internal/db/bundb/instance.go
> +		q = q.WhereGroup(" AND ", whereEmptyOrNull("domain"))
I meant just so we have a clear definition in the database between empty column value, and null column value. Null should mean it hasn't been entered, and empty that an empty value was supplied. Though it's not a hugely important point, and maybe me not understanding things correctly :p

2021-08-28 12:39 UTC, tsmethurst commented on internal/federation/dereferencing/status.go
> +	newMentions := []*gtsmodel.Mention{}
I see what you mean, but because the function continues if something goes wrong, that could mean we end up with half-finished mentions still being attached to the status. The reason i took a new slice was to make sure we only pin valid mentions on the status, instead of enriching some and potentially leaving others dangling unfinished. Will add already-populated mentions and ids to the slice(s) though, well spotted, totally missed that one!

2021-08-28 12:44 UTC, tsmethurst commented on internal/federation/dereferencing/status.go
> +		if replyToStatus == nil {
You're right indeed -- we should check nil at the database level probably, rather than individual functions though. I'll change this code for now to remove the nil check, and let's put it in the database fixup we have in the pipeline, what do you think?

2021-08-28 13:10 UTC, tsmethurst commented on internal/federation/dereferencing/attachment.go
> +	if !refresh {
I've tried to do this in the changes i just pushed, but it's a bit tricky to cut down the variables and there are still quite a lot... There's probably a neater way of doing it that involves reworking some of the media handler logic a little bit

2021-08-29 09:17 UTC, NyaaaWhatsUpDoc commented on internal/federation/dereferencing/status.go
> +		if replyToStatus == nil {
Sounds good to me!

2021-08-29 09:22 UTC, NyaaaWhatsUpDoc approved these changes

2021-08-29 10:03 UTC, merged