Improve GetRemoteStatus and db.GetStatus() logic
superseriousbusiness/gotosocial pull request #174
Opened 2021-08-30 19:20 UTC by NyaaaWhatsUpDoc

- removes chance of db.GetStatus() recursion
- improves GetRemoteStatus() to require specifying if parent / children are required in status
- fix StatusCache to return object copies, and only store information about status itself (not related attachments)
- set `cache=shared` by default on SQLite instances to ensure thread-safety between operations (this was the source of the `nested transaction` related errors we were seeing). why this was not set as a default in a Go library where you have to go out of your way to run single-threaded?! who knows

2021-08-30 19:36 UTC, NyaaaWhatsUpDoc commented
Snuck in another bugfix with a panic caused by EnrichRemoteAccount :)

2021-08-31 08:48 UTC, tsmethurst requested changes
Just the testing stuff needs to change, the rest looks great :+1:

2021-09-01 07:28 UTC, NyaaaWhatsUpDoc commented on internal/db/bundb/account.go
> +func (a *accountDB) getAccount(ctx context.Context, cacheGet func() (*gtsmodel.Account, bool), dbQuery func(*gtsmodel.Account) error) (*gtsmodel.Account, db.Error) {
Yep I will handle that when that PR is merged :)

2021-09-01 07:28 UTC, NyaaaWhatsUpDoc commented on internal/cache/account_test.go
> +func TestAccountCache(t *testing.T) {
Done :+1:

2021-09-01 07:28 UTC, NyaaaWhatsUpDoc commented on internal/db/bundb/bundb.go
> +		// Drop anything fancy from DB address
I'll add an issue for it

2021-09-01 07:29 UTC, NyaaaWhatsUpDoc commented on internal/db/bundb/relationship.go
> +			Join("JOIN accounts AS a ON follow.account_id = CAST(a.id as TEXT)").
I just added tests for this (and the other relationship SQL change) to make sure!

2021-09-01 07:41 UTC, NyaaaWhatsUpDoc commented on internal/db/bundb/relationship.go
> +			Join("JOIN accounts AS a ON follow.account_id = CAST(a.id as TEXT)").
The tests seem to pass! As long as you can confirm these tests look good enough to check the SQL syntax I'd say this is ready :D

2021-09-01 08:56 UTC, tsmethurst commented on internal/db/bundb/relationship_test.go
> +		if err != nil && !errors.Is(err, db.ErrNoEntries) {
you can just do `suite.Error(err)` here to assert an error, or even better do `suite.EqualError(err, db.ErrNoEntries)`

2021-09-01 08:56 UTC, tsmethurst commented on internal/db/bundb/relationship_test.go
> +		if err != nil {
`suite.NoError(err)`

2021-09-01 08:56 UTC, tsmethurst commented on internal/db/bundb/relationship_test.go
> +		if err != nil {
`suite.NoError(err)`

2021-09-01 08:56 UTC, tsmethurst commented on internal/db/bundb/relationship_test.go
> +	suite.Suite.T().Skip("TODO: implement")
for all these I think you can just do `suite.T()` instead of `suite.Suite.T()`

2021-09-01 09:08 UTC, tsmethurst approved these changes

2021-09-01 09:08 UTC, merged