Thread views on the web
superseriousbusiness/gotosocial pull request #207
Opened 2021-09-10 20:56 UTC by f0x52

Implementation for #175. Also includes the new CSS bundling setup

2021-09-11 08:08 UTC, tsmethurst requested changes
Mostly looks fucking GREAT! <3 Just a few little comments/potential changes/questions. Really excited about this :D

2021-09-11 08:08 UTC, tsmethurst commented on web/template/status.tmpl
> +			 		<div class="no-image-desc" aria-hidden="true" >(!)<span>Missing image description</span></div>
is it possible to use something from FA instead of the literal `(!)`?

2021-09-11 08:08 UTC, tsmethurst commented on internal/web/thread.go
> +	authed, err := oauth.Authed(c, false, false, false, false) // we don't really need an app here but we want everything else
you might as well drop the line comment here, since it doesn't really apply :P

2021-09-11 08:08 UTC, tsmethurst commented on internal/web/thread.go
> +	instance, err := m.processor.InstanceGet(c.Request.Context(), m.config.Host)
since you're using c.Request.Context() several times, you can just define it at the top as something like `ctx := c.Request.Context()` and then pass that in to the processor functions, it's a bit neater

2021-09-11 08:08 UTC, tsmethurst commented on internal/web/thread.go
> +	if err := c.ShouldBindUri(&statusLink); err != nil {
COOL, I didn't know this was possible!

2021-09-11 08:08 UTC, tsmethurst commented on internal/web/thread.go
> +type StatusLink struct {
can you make this unexported if you're just using it here? (ie., use lower-camel instead of upper-camel.) Does it still work then?

2021-09-11 08:08 UTC, tsmethurst commented on testrig/testmodels.go
> +			DisplayName:             "Admin",
in cases where no display name is set, we should just use the 'username' instead, does the templating allow for this?

2021-09-11 08:08 UTC, tsmethurst commented on testrig/testmodels.go
> +			Description:       "",
Were these changes a left over from testing maybe? :P

2021-09-13 12:16 UTC, tsmethurst commented on internal/router/template.go
> +	println("loading html templates")
best drop this or convert it to log with logrus

2021-09-13 12:17 UTC, tsmethurst commented on internal/web/thread.go
> +	println(uriParts.User[:1], uriParts.User, status.Account.Username)
same comment as above println call

2021-09-13 12:18 UTC, tsmethurst commented on testrig/testmodels.go
> +			AttachmentIDs:            []string{"01F8MH6NEM8D7527KZAECTCR76", "01F8MH7TDVANYKWVE8VVKFPJTJ", "01F8MH8RMYQ6MSNY3JM2XT1CQ5"},
do you still need the changes in this file?

2021-09-13 12:19 UTC, f0x52 commented on testrig/testmodels.go
> +			AttachmentIDs:            []string{"01F8MH6NEM8D7527KZAECTCR76", "01F8MH7TDVANYKWVE8VVKFPJTJ", "01F8MH8RMYQ6MSNY3JM2XT1CQ5"},
oh not really, but it would be good to have a test thread with a bunch of images populated

2021-09-13 12:45 UTC, merged