add authentication workflow to docs
superseriousbusiness/gotosocial pull request #2655
Opened 2024-02-18 05:23 UTC by fyrfli

# Add the api authentication workflow to the documentation

> If this is a code change, please include a summary of what you've coded, and link to the issue(s) it closes/implements.
>
> If this is a documentation change, please briefly describe what you've changed and why.

This pull request adds the api authentication workflow to the documents and addresses #(1135).

closes #(1135)

## Checklist

Please put an x inside each checkbox to indicate that you've read and followed it: `[ ]` -> `[x]`

If this is a documentation change, only the first checkbox must be filled (you can delete the others if you want).

- [x] I/we have read the [GoToSocial contribution guidelines](https://github.com/superseriousbusiness/gotosocial/blob/main/CONTRIBUTING.md).
- [x] I/we have discussed the proposed changes already, either in an issue on the repository, or in the Matrix chat.
- [x] I/we have not leveraged AI to create the proposed changes.
- [ ] I/we have performed a self-review of added code.
- [ ] I/we have written code that is legible and maintainable by others.
- [ ] I/we have commented the added code, particularly in hard-to-understand areas.
- [ ] I/we have made any necessary changes to documentation.
- [ ] I/we have added tests that cover new code.
- [ ] I/we have run tests and they pass locally with the changes.
- [ ] I/we have run `go fmt ./...` and `golangci-lint run`.

2024-02-18 12:43 UTC, daenney requested changes

2024-02-18 12:43 UTC, daenney commented on docs/api/authentication.md
> +GoToSocial implements an API that is compatible with the Mastodon API which means that most everything to do with the API follows many of the conventions and techniques that work for the Mastodon API
I would suggest moving this to either the `swagger.md`, as that's the introduction page for the API section, or dropping it. It's generally understood that alternative implementations provide a Mastodon-compatible Client API.

2024-02-18 12:43 UTC, daenney commented on docs/api/authentication.md
> +We need to get a new key:pair for our application. This is done by making a `POST` request to the `/api/v1/apps` endpoint. Replace `your_app_name` in the code below:
```suggestion
We need to get a new key pair for our application. This is done by making a `POST` request to the `/api/v1/apps` endpoint. Replace `your_app_name` in the code below:
```

2024-02-18 12:43 UTC, daenney commented on docs/api/authentication.md
> +  "redirect_uris": "urn:ietf:wg:oauth:2.0:oob",
I would add an explanation after this code sample for why `urn:ietf:wg:oauth:2.0:oob` specifically.

2024-02-18 12:43 UTC, daenney commented on docs/api/authentication.md
> +A successful call returns a response with a client_id and client_secret that we are going need to use in the rest of the process. It looks something like this:
```suggestion
A successful call returns a response with a `client_id` and `client_secret` that we are going need to use in the rest of the process. It looks something like this: 
```

2024-02-18 12:43 UTC, daenney commented on docs/api/authentication.md
> +```
```suggestion
```json
```

2024-02-18 12:43 UTC, daenney commented on docs/api/authentication.md
> +## authorizing your application
```suggestion
## Authorizing your application
```

2024-02-18 12:43 UTC, daenney commented on docs/api/authentication.md
> +    Ensure you save the client_id and client_secret somewhere so you can refer to it as we go.
```suggestion
    Ensure you save the `client_id` and `client_secret` somewhere so you can refer to it as we go.
```

2024-02-18 12:43 UTC, daenney commented on docs/api/authentication.md
> +We've registered a new application with GoToSocial, but it isn't connected to your account just yet. Now we need to tell GoToSocial that that new application is actually going to interact as you. To
```suggestion
We've registered a new application with GoToSocial, but it isn't connected to your account just yet. Now we need to tell GoToSocial that that new application is actually going to act on your behalf. To do this, we need to authenticate with your instance via a browser to initiate the login and permission granting process.
```

2024-02-18 12:43 UTC, daenney commented on docs/api/authentication.md
> +!!! important
```suggestion
!!! tip
```

`important` isn't a recognised admonition, so it renders just like Note. I think `tip` is suitable here instead.

2024-02-18 12:43 UTC, daenney commented on docs/api/authentication.md
> +!!! note
I would change this to a code block. Admonitions are for callouts or separate calls to action. I wouldn't use them to display the response of and endpoint or result of an action.

2024-02-18 12:43 UTC, daenney commented on docs/api/authentication.md
> +!!! note
Idem here, this should be a code block.

2024-02-18 12:43 UTC, daenney commented on docs/api/authentication.md
> +```
```suggestion
```json
```

2024-02-18 12:43 UTC, daenney commented on docs/api/authentication.md
> +To make sure everything went through successfully, target the `/api/v1/verify_credentials` endpoint, adding your new access token to the Header as `Authentication:Bearer your_brand_new_token`.
```suggestion
To make sure everything went through successfully, query the `/api/v1/verify_credentials` endpoint, adding your new access token to the Header as `Authorization: Bearer your_brand_new_token`.
```

2024-02-18 12:43 UTC, daenney commented on docs/api/authentication.md
> +---
```suggestion
```

The headers already create separate sections, we don't really need additional horizontal lines here.

2024-02-18 12:44 UTC, daenney commented
Overall this looks pretty great. I have some small stylistic/markup changes and once those get resolved I think this should be good to go!

2024-02-18 12:48 UTC, daenney commented on docs/api/authentication.md
> +GoToSocial implements an API that is compatible with the Mastodon API which means that most everything to do with the API follows many of the conventions and techniques that work for the Mastodon API
If you want to keep an intro paragraph, I would go with something like "Using the client API requires authentication. This page documents the general flow for retrieving an authentication token with examples for doing this on the CLI".

2024-02-18 15:13 UTC, fyrfli commented
sweet ... thanks for these. i will try and have them done today

2024-02-18 18:09 UTC, daenney commented
No worries, it's the weekend! We'll be here all of next week :wink:.

2024-02-18 20:30 UTC, fyrfli commented on docs/api/authentication.md
> +!!! note
maybe use a quote block instead?

2024-02-18 20:33 UTC, fyrfli commented on docs/api/authentication.md
> +```
question: would it be helpful to use ```bash for the curl lines?

2024-02-18 20:36 UTC, fyrfli commented on docs/api/authentication.md
> +GoToSocial implements an API that is compatible with the Mastodon API which means that most everything to do with the API follows many of the conventions and techniques that work for the Mastodon API
done. i hope it's ok to use your suggestion as is for this. i did want some kind of intro paragraph, but i wrote it independently in obsidian and copied it directly into a new file, which is how i got that somewhat redundant paragraph.

2024-02-18 20:37 UTC, fyrfli commented on docs/api/authentication.md
> +  "redirect_uris": "urn:ietf:wg:oauth:2.0:oob",
to be honest, i had to go searching for what it means because *i* didn't know what it meant.

2024-02-19 07:15 UTC, daenney commented on docs/api/authentication.md
> +To make sure everything went through successfully, query the `/api/v1/verify_credentials` endpoint, adding your new access token to the Header as `Authentication: Bearer your_brand_new_token`.
```suggestion
To make sure everything went through successfully, query the `/api/v1/verify_credentials` endpoint, adding your new access token to the Header as `Authorization: Bearer your_brand_new_token`.
```

2024-02-19 07:16 UTC, daenney reviewed
Thanks for resolving the comments! There's one with a wrong header name and after that I think we're good to go.

2024-02-19 10:32 UTC, fyrfli commented
done. surprised i missed that especially since i caught a few other typos earlier.

2024-02-19 10:35 UTC, fyrfli commented
my pleasure. i've been looking for the opportunity to contribute for a while.

2024-02-19 10:40 UTC, daenney commented
I'll leave it open for a day or two so the rest of the team has the opportunity to go through it too. If it doesn't get merged by anyone else I'll click the button on Wednesday.

2024-02-19 10:50 UTC, tsmethurst commented
This is looking good :) I'll have a proper look through it this afternoon. Thanks for doing this!

Linking this issue because it's relevant: https://github.com/superseriousbusiness/gotosocial/issues/2421

2024-02-21 13:07 UTC, tsmethurst commented on docs/api/authentication.md
> +We need to get a new key pair for our application. This is done by making a `POST` request to the `/api/v1/apps` endpoint. Replace `your_app_name` in the code below:
Key pair is a bit confusing here because it suggests that cryptography is involved somehow. I'd just say something like:

```suggestion
We need to register a new application, which we can then use to request an OAuth token. This is done by making a `POST` request to the `/api/v1/apps` endpoint. Replace `your_app_name` in the code below:
```

2024-02-21 13:08 UTC, tsmethurst commented on docs/api/authentication.md
> +      "client_name": your_app_name,
I'd wrap this as a string as well so that callers don't try to provide it as a bare value.

```suggestion
      "client_name": "your_app_name",
```

2024-02-21 13:10 UTC, tsmethurst commented on docs/api/authentication.md
> +    Be **very** careful what scopes you grant to your application.
To avoid lulling people into a false sense of security, I think it would be a good idea to add a note here that GoToSocial does not currently support proper scopes on tokens. This is something we still need to add during the beta phase (this year).

2024-02-21 15:52 UTC, fyrfli commented on docs/api/authentication.md
> +    Be **very** careful what scopes you grant to your application.
So, something along the lines of:

"While GoToSocial does not currently support properly scoped tokens, it is still good practice to grant your application the lowest level permissions it needs to do its job. e.g. if your application won't be making posts, limit it to scope=read."

2024-02-22 14:28 UTC, mirabilos commented on docs/api/authentication.md
> +- push
I can sort of guess what the scopes read, write, follow and admin do, but push not so much. Maybe add a description of the scopes as relating to GtS or (maybe better) link to one?

2024-02-22 15:33 UTC, mirabilos commented on docs/api/authentication.md
> +
OK, good point.

Is there an API to remove apps yet?

2024-02-22 20:57 UTC, fyrfli commented on docs/api/authentication.md
> +- push
Funnily, I copied that directly from the mastodon docs assuming the API is implemented in whole. My mistake. To your specific point: I have no idea how one would implement "push" permission. From the mastodon docs:

> Grants access to [Web Push API subscriptions.](https://docs.joinmastodon.org/methods/push/) Added in Mastodon 2.4.0.

Do we even have that feature/facility/functionality in Gts?

Re-reading the docs, it also seems as if follow is depreacted in favour of "child permissions" instead (read:follows, write:follows, etc.). So I will remove that on next commit as well.

2024-02-22 20:58 UTC, fyrfli commented on docs/api/authentication.md
> +
I have used tinysubversions before for my akkoma install but I agree that that should be an individual decision to use so that we don't expose ourselves as a project.

2024-02-22 21:40 UTC, mirabilos commented on docs/api/authentication.md
> +- push
Probably best to align here with what GtS supports, and possibly indicate what was added in which GtS version starting from when it becomes beta or so.

2024-02-22 23:27 UTC, tsmethurst commented on docs/api/authentication.md
> +- push
Description of what scopes do is not in scope for this PR, which is just about how to go through the authorization flow to get a token. And token scopes are not implemented yet anyway, as mentioned in the warning box below. Once they are, we can revisit this bit of the docs and add appropriate links. So I think this is fine for now :)

2024-02-23 06:11 UTC, fyrfli commented on docs/api/authentication.md
> +- push
Which makes me think I should remove "follow and "push" since they are outdated in home mastodon anyway? And leave the rest as is?

Thoughts?

2024-02-23 11:05 UTC, tsmethurst commented on docs/api/authentication.md
> +- push
> I should remove "follow and "push"

Mmm. I thought about it a bit more; we probably could just replace all this stuff about scopes with something like:

```
!!! warning
   GoToSocial does not currently support scoped authorization tokens, so any token you obtain in this process will be able to perform all actions on your behalf. Nevertheless, it is always good practice to grant your application the lowest tier permissions it needs to do its job. e.g. If your application won't be making posts, use scope=read.
   
   In this spirit, "read" is used in the example above, which means that in the future when scoped tokens are supported, the application will be restricted to only being able to do "read" actions.
   
   You can read more about additional planned OAuth security features [right here](https://github.com/superseriousbusiness/gotosocial/issues/2232).
```

Then we're really not giving any false impressions that we support scoped tokens yet. What do you think?

2024-02-23 15:08 UTC, mirabilos commented on docs/api/authentication.md
> +- push
That, but perhaps mention explicitly that that includes administrative access as well if the token is for an admin account. (I thought a read/write token would explicitly not do that but…)

2024-02-23 15:26 UTC, tsmethurst commented on docs/api/authentication.md
> +- push
Edited the above to mention that ^

2024-02-24 03:45 UTC, fyrfli commented on docs/api/authentication.md
> +- push
Alrighty. Apologies for only getting to this now. For some reason notifications stopped coming through either in email or in the app. Applied that change to the warning immediately following the scopes discussion and removed push/follow from the list.

2024-02-24 08:39 UTC, tsmethurst commented on docs/api/authentication.md
> +- push
> Apologies for only getting to this now.

No problem at all, nothing to apologize for :)

2024-02-24 08:41 UTC, merged

2024-02-24 08:41 UTC, tsmethurst commented
Merged it! :) Thank you very much for this!

2024-02-24 17:37 UTC, fyrfli commented
It was my pleasure! I love this project!