[feature/performance] Store account stats in separate table
superseriousbusiness/gotosocial pull request #2831
Opened 2024-04-14 14:36 UTC by tsmethurst

# Description

> If this is a code change, please include a summary of what you've coded, and link to the issue(s) it closes/implements.
>
> If this is a documentation change, please briefly describe what you've changed and why.

This pull request changes the way we generate account stats. Previously, we were caching some stats in an in-memory cache. Before that, we just selected stats directly using COUNT queries every time an account needed to viewed via the API.

Instead in this PR stats are now stored in the database, and a best-effort is made to keep those stats up to date in the processing/worker functions.

This also means that we can now parse remote followers/following counts and store those, instead of having remote accounts always show counts only for local followers/following. 

Some new functionality has been added to the cleaner package as well: every 24hrs at 1am a new "database cleaner" function will run. Currently this just regenerates stats for local accounts to prevent possible drift due to race conditions, but in future we could also use this new cleaner functionality to clean up old statuses when we get around to implementing that.

Should close https://github.com/superseriousbusiness/gotosocial/issues/1887

Draft because I wanna write some tests :)

## Checklist

Please put an x inside each checkbox to indicate that you've read and followed it: `[ ]` -> `[x]`

If this is a documentation change, only the first checkbox must be filled (you can delete the others if you want).

- [x] I/we have read the [GoToSocial contribution guidelines](https://github.com/superseriousbusiness/gotosocial/blob/main/CONTRIBUTING.md).
- [x] I/we have discussed the proposed changes already, either in an issue on the repository, or in the Matrix chat.
- [x] I/we have not leveraged AI to create the proposed changes.
- [x] I/we have performed a self-review of added code.
- [x] I/we have written code that is legible and maintainable by others.
- [x] I/we have commented the added code, particularly in hard-to-understand areas.
- [ ] I/we have made any necessary changes to documentation.
- [ ] I/we have added tests that cover new code.
- [x] I/we have run tests and they pass locally with the changes.
- [x] I/we have run `go fmt ./...` and `golangci-lint run`.

2024-04-14 20:59 UTC, NyaaaWhatsUpDoc commented on internal/ap/collections.go
> +func (iter *orderedCollectionIterator) TotalItems() *int {
i think since you're returning a signed int anyways, instead of making this a ptr in the case of no total it's probably worth returning -1 instead

2024-04-14 21:17 UTC, NyaaaWhatsUpDoc commented on internal/cleaner/database.go
> +type Database struct {
i'm not sure this is something we need to regenerate on a scheduled basis given the increment / decrement functions in the processor. the onlly time it *may* fall out of sync is possibly during a restart / panic, so instead of having it be a scheduled thing i think instead it would worth adding it as an admin CLI + frontend command. otherwise this is a very likely relatively expensive for not often any change database operation we're scheduling every day. *alternatively* if we schedule it on a longer time frame than that it runs into the situation that if you restart semi often then the schedule may never get used. i feel like making it an admin command mitigates these issues. what do you think?

2024-04-14 21:21 UTC, NyaaaWhatsUpDoc commented
a few comments so far, and i need to spend some more time thinking about the client locks just to make sure there isn't an issue, but otherwise looking good so far!

2024-04-14 21:22 UTC, NyaaaWhatsUpDoc commented on internal/cleaner/database.go
> +type Database struct {
this also leaves the option for selecting to regenerate local-only accounts, and remote-only accounts. the latter of which allows someone that wants them to run a long operation to ensure **all** the accounts in their database are up-to-date (even if statuses is only *our* count of them)

2024-04-14 21:28 UTC, NyaaaWhatsUpDoc commented on internal/cleaner/database.go
> +type Database struct {
or actually, just thought of a solution that solves this situation **perfectly** :D: if we moved this operation from being a scheduled operation, to instead run on instance start. we're only running it for local accounts, so it should be a fast one, and it perfectly handles the case of increments / decrements not happening on restart due to workers shutting down!

2024-04-14 21:29 UTC, NyaaaWhatsUpDoc commented on internal/cleaner/database.go
> +type Database struct {
but maybe offering it as an admin CLI option (configurable to be local / remote) so admins can force recheck for their remote accounts if they want to?

2024-04-15 08:36 UTC, tsmethurst commented on internal/cleaner/database.go
> +type Database struct {
Hmmmm I see what you mean.... What if I were to add a field `RegeneratedAt` to AccountStats, and if, when doing a GetAccountStats, that timestamp is older than say 48 hours, it gets regenerated? For local accounts only. That's the "lazy" way of doing it, but I think it solves most of the problems above... What do you think?

2024-04-15 08:37 UTC, tsmethurst commented on internal/cleaner/database.go
> +type Database struct {
(For remote accounts this stuff gets pulled again when the account gets refreshed anyways, which I think is on a 6hr cooldown iirc)

2024-04-15 08:50 UTC, NyaaaWhatsUpDoc commented on internal/cleaner/database.go
> +type Database struct {
that would work, though i'm just a bit apprehensive to add scheduled tasks unless we *really* need them. you could just make it run on instance start, and a later PR actually expose it as an admin CLI thing?

2024-04-15 08:58 UTC, tsmethurst commented on internal/cleaner/database.go
> +type Database struct {
Ah no no, I don't mean running it as a scheduled task, I'll take that bit out :) I mean similar to what we do now with remote accounts, where we refresh them if FetchedAt is older than six hours, we'll regenerate local account stats when doing GetAccountStats if RegeneratedAt is older than 48 hrs or some similar number :)

2024-04-15 10:06 UTC, tsmethurst commented on internal/ap/collections.go
> +func (iter *orderedCollectionIterator) TotalItems() *int {
Done!

2024-04-15 10:22 UTC, tsmethurst commented on internal/cleaner/database.go
> +type Database struct {
Done!

2024-04-15 13:41 UTC, NyaaaWhatsUpDoc requested changes

2024-04-15 13:41 UTC, NyaaaWhatsUpDoc commented on internal/federation/dereferencing/account.go
> +		log.Debugf(ctx,
i'd maybe make this a warning level error, it's something that's useful for admins to see in the logs in terms of troubleshooting

2024-04-15 13:41 UTC, NyaaaWhatsUpDoc commented on internal/federation/dereferencing/account.go
> +		log.Debugf(ctx,
or actually saying that, given there's logging in the caller of this function (and it's not handled as being a showstopper), probably just worth returning this as an error here

2024-04-15 13:41 UTC, NyaaaWhatsUpDoc commented on internal/db/bundb/account.go
> +func (a *accountDB) GetAccountStats(ctx context.Context, accountID string) (*gtsmodel.AccountStats, error) {
given that this is often called to populate an account model to begin with, what do you think if you updated the function signature of this to be `GetAccountStatus(ctx context.Context, account *gtsmodel.Account) error` ? it just saves needed to do the double fetch of an account model that's likely already there.

2024-04-15 13:43 UTC, NyaaaWhatsUpDoc commented on internal/processing/workers/util.go
> +	// Populate stats.
probably worth using a client lock for each of these increment / decrement functions :)

2024-04-16 10:36 UTC, tsmethurst commented on internal/db/bundb/account.go
> +func (a *accountDB) GetAccountStats(ctx context.Context, accountID string) (*gtsmodel.AccountStats, error) {
Done! https://github.com/superseriousbusiness/gotosocial/pull/2831/commits/9ff5e0cbabdecd32b86fe64d0acf6ec15097cb40

2024-04-16 10:45 UTC, tsmethurst commented on internal/federation/dereferencing/account.go
> +		log.Debugf(ctx,
Alright, rejigged it here and changed it to warn logging from error level as it's not critical: https://github.com/superseriousbusiness/gotosocial/pull/2831/commits/9d15127841fa81ed1713c0c5963f2aa632f3a58f

2024-04-16 10:54 UTC, tsmethurst commented on internal/processing/workers/util.go
> +	// Populate stats.
Good idea! Changed it here: https://github.com/superseriousbusiness/gotosocial/pull/2831/commits/ceb84e55ee2facd2a7263c77c97c431e42b99f3e I also renamed "ClientLocks" to "AccountLocks" since we were using it for more than just ClientAPI actions, and also we're using it just for account URIs (I checked).

2024-04-16 11:10 UTC, merged