Refactor media handler to allow async media resolution
superseriousbusiness/gotosocial pull request #361
Opened 2022-01-15 16:58 UTC by tsmethurst

This PR represents a significant rework of the media processing functionality of GoToSocial, which was old code written near the start of the project.

The new 'media manager' that replaces the 'media handler' has several advantages over the old way of doing things, mostly performance-based:

* Allow asynchronous processing of media (avatars, headers, attachments, emoji) by returning an 'inProcess' struct that works sort of like a promise: caller can either resolve the media immediately (blocking), or get on with other work and assume media will be processed in the background. This should solve the issue of requests timing out on slower machines, while media processing was being done synchronously.
* Use a worker pool to ensure that only a limited number of media processes are running concurrently (by default, number of CPUs divided by 2, always at least 1). This should avoid media processing killing lower-powered machines by eating up all the CPU cycles.
* Allow callers of the media manager to provide a function that will return bytes, rather than the raw bytes themselves. This means that requests to external resources (other instances) will only be made when a worker picks up the job, rather than ballooning memory use by storing lots of bytes in RAM while processing.
* Only process blurhashes when necessary. Where possible, use the blurhash already calculated by the remote instance.

2022-01-16 17:54 UTC, tsmethurst commented
Failing linting because I still need to figure out the best way of purging exif data from images. Don't worry, i'm aware of it :)

2022-01-29 11:22 UTC, tsmethurst commented on internal/federation/dereferencing/account.go
> +func (d *deref) fetchRemoteAccountMedia(ctx context.Context, targetAccount *gtsmodel.Account, t transport.Transport, blocking bool, refresh bool) (bool, error) {
Note to reviewers: this function changed a lot and it does some fiddly stuff with locks and goroutines: worth a close look I think.

2022-01-29 11:23 UTC, tsmethurst commented on internal/media/image.go
> +/*
The meat and potatoes of image processing is in here

2022-01-29 11:24 UTC, tsmethurst commented on internal/media/manager.go
> +func (m *manager) ProcessMedia(ctx context.Context, data DataFunc, accountID string, ai *AdditionalMediaInfo) (*ProcessingMedia, error) {
This function and the one below it are where media processing jobs enter the queue

2022-02-07 17:10 UTC, NyaaaWhatsUpDoc requested changes

2022-02-08 09:17 UTC, tsmethurst commented on internal/typeutils/internaltoas.go
> +			if err == nil {
Mainly so that we can still serve something to the caller even if there's an issue with fetching the avatar/header. Although now that you mention it, we should not swallow the error. I'll change it to log an error if there is one.

2022-02-08 11:39 UTC, tsmethurst commented on internal/typeutils/internaltoas.go
> +			if err == nil {
Fixed: https://github.com/superseriousbusiness/gotosocial/pull/361/commits/c4ece24654e195dbff06c1d7363c5fe92e1fd4c4

2022-02-08 12:18 UTC, tsmethurst commented on internal/federation/dereferencing/account.go
> +			d.dereferencingAvatars[targetAccount.ID] = newProcessing
Hopefully fixed here: https://github.com/superseriousbusiness/gotosocial/pull/361/commits/dba9ad434885603b85938386a4681350698decac

2022-02-08 12:39 UTC, tsmethurst commented on internal/media/processingemoji.go
> +	return p.staticState == complete && p.fullSizeState == complete
https://github.com/superseriousbusiness/gotosocial/pull/361/commits/8c0141d103cb70fdbe74f1d5a936860707da973f

2022-02-08 12:39 UTC, tsmethurst commented on internal/media/processingmedia.go
> +	return p.thumbstate == complete && p.fullSizeState == complete
https://github.com/superseriousbusiness/gotosocial/pull/361/commits/8c0141d103cb70fdbe74f1d5a936860707da973f

2022-02-12 18:25 UTC, NyaaaWhatsUpDoc commented on internal/federation/dereferencing/account.go
>  	if err == nil {
don't worry about this, if i can be bothered i might submit a refactor PR at a later date :p, it has zero effect on logic / performance

2022-02-12 18:26 UTC, NyaaaWhatsUpDoc approved these changes

2022-02-12 18:27 UTC, merged