docs: unify nginx explainers and add apache httpd
superseriousbusiness/gotosocial pull request #455
Opened 2022-04-15 21:52 UTC by igalic

there are two places where nginx + certbot is explained, unify that into one place.
Add apache httpd, following the same steps, but using mod_md for LetsEncrypt
add a note about #453 in both guides.
Link to both, and call the section reverse proxy, instead of NGINX

2022-04-15 21:57 UTC, igalic commented on docs/installation_guide/nginx.md
> +Reload it one last time and after that you should be good to go!
tuning language here, removing "just"

2022-04-15 21:57 UTC, igalic commented on docs/installation_guide/binary.md
> +If you want to run other webservers on port 433 or want to add an additional layer of security you might want to use [nginx](./nginx.md) or [Apache httpd](./apache-httpd.md) as reverse proxy
tuning language here: removing simply

nothing in software is simple

2022-04-15 21:57 UTC, igalic commented on docs/installation_guide/nginx.md
> +**Note***: You can remove the line `listen [::]:80;` if your server is not ipv6 capable.
removing the bit about not wanting to bother with IPv6 👀

2022-04-15 21:57 UTC, igalic commented on docs/installation_guide/docker.md
> -  ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
this whole section needs to be a link to documentation somewhere on how to harden nginx' SSL config
and it shouldn't be in the docker part.

2022-04-15 21:57 UTC, igalic commented on docs/installation_guide/apache-httpd.md
> +# Reverse proxy with Apache httpd
this whole document is basically copy-paste from your nginx document.

2022-04-15 21:57 UTC, igalic commented on docs/installation_guide/apache-httpd.md
> +To setup Apache httpd with mod_md, we'll need to load the module and then modify our vhost files:
except for this section.

2022-04-15 21:58 UTC, igalic commented
i don't know why the build is failing
(it wasn't me)

2022-04-16 10:04 UTC, tsmethurst commented on docs/installation_guide/docker.md
> -  ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
Agreed it shouldn't be in the docker section, however I think instead of totally deleting it we should merge it with the existing nginx example in the nginx.md document. Can you do that?

2022-04-16 10:05 UTC, tsmethurst requested changes
Looks good, just the comment I added, and also you still need to add this to the mkdocs.yml in the root of the repo so it appears in the documentation properly.

2022-04-16 10:27 UTC, igalic commented
i think i can, and i can use #441 for picking out some details and pointers
might take a while *\*points at toddler\**

2022-04-16 10:54 UTC, tsmethurst commented
No rush :)

2022-04-16 21:45 UTC, igalic commented
added mkdocs entry
and restored big nginx.conf and i have absolutely nothing to add to it, because well, i still don't know how nginx works.

2022-04-18 15:45 UTC, merged