new styling for frontpage, update login and authorize templates
superseriousbusiness/gotosocial pull request #46
Opened 2021-06-18 22:16 UTC by f0x52

Basic implementation for #32  and also updates the login and authorize templates to match the styling.

Source lives at `web/source/style.css`, which is transpiled to browser-usable css with `web/source/build.js` which depends on postcss. A pre-bundled version is included at `web/assets/bundle.css` so instance owners don't *have* to install node + the dependencies unless they want to change color variables

2021-06-18 22:17 UTC, f0x52 commented
TODO: maybe CI thingie to automatically rebuild the bundle on changes?

2021-06-19 07:46 UTC, tsmethurst requested changes
Mostly looks good, just gotta figure out where to put the '/' route, and add the CLI flag

2021-06-19 07:46 UTC, tsmethurst commented on internal/router/router.go
> +	// FIXME: why doesn't this config var work??
Looks like you didn't yet add it as a CLI flag in `cmd/gotosocial/main.go`, which is where the parsing of config is initiated.

2021-06-19 07:46 UTC, tsmethurst commented on internal/router/router.go
> +	engine.GET("/", func(c *gin.Context) {
imo this should be moved from the router to something like `/internal/web/base` to bring it in line with the way the client api and S2S api are structured, and it should be set up as a module so that a router is passed to it (take a look at any of the client API modules -- the statuses one is a good example). What do you think? Maybe having it as internal/web is a bit confusing though? Not sure.

2021-06-19 07:46 UTC, tsmethurst commented on web/template/authorize.tmpl
> +{{ template "header.tmpl" .}}
god, so much cleaner <3

2021-06-19 07:46 UTC, tsmethurst commented on web/template/footer.tmpl
> +			<a href="/moderation">Moderation team</a>
I'm not sure yet what moderation system to actually put in place for GtS. I was even considering (although this adds complexity, obviously) giving the instance admin the ability to choose between having a traditional moderation team, or implementing some kind of community moderation option where instance users can vote on decisions.

For now this is good, it just got me thinking again about this :P

2021-06-19 07:46 UTC, tsmethurst commented on web/template/index.tmpl
> +	<h3>This is the default landing page, you can edit it from <span class="accent">./web/template/index.tmpl</span></h1>
I like this!

2021-06-19 12:37 UTC, tsmethurst commented on internal/web/base.go
> +package base
OK now I'm seeing this it occurs to me that since there are gonna be a bunch of web pages available (user profiles, statuses -- if they're public, moderation, maybe a list of blocked instances or something), we should actually move this up a level to package `web` and then have that Module attach a few different handlers through the `Route` function, that all have common cause in serving HTML via a web request. For helping to populate the templates, we should also pass a pointer to the `Processor` interface into the Module, as is done in most of the Client API and S2S modules. Then if Handlers need, say, a user count or some other information that's not just in config, they can call a function in the processor to retrieve that information before returning.

What do you think?

2021-06-19 12:38 UTC, tsmethurst commented on internal/web/base.go
> +package base
This will also be useful in cases I foresee in the future, where users have set a specific template for a public status that they want to be available, and the Handler will need to know which template is used and fall back to a default if none has been manually selected.

2021-06-21 17:46 UTC, tsmethurst approved these changes

2021-06-21 17:46 UTC, merged