[documentation] NGINX docs updates
superseriousbusiness/gotosocial pull request #471
Opened 2022-04-19 13:38 UTC by tsmethurst

Some updates to the NGINX documentation.

* Add websockets options.
* Replace explicit security hardening with a recommendation.
* Stop GoToSocial while the procedure is happening.

2022-04-21 19:43 UTC, igalic requested changes
looks good.
just minor change.

2022-04-21 19:43 UTC, igalic commented on docs/installation_guide/nginx.md
> +Or if you don't have a systemd service just stop it manually.
just?
how?
`Ctrl+C` ? `pkill`?

2022-04-21 19:43 UTC, igalic commented on docs/installation_guide/nginx.md
> +**Note**: The `Connection` and `Upgrade` headers are used for WebSocket connections.
We can later link to the websocket doc here.

2022-04-23 11:53 UTC, tsmethurst commented on docs/installation_guide/nginx.md
> +**Note**: The `Connection` and `Upgrade` headers are used for WebSocket connections.
I'll do that before I pull it in

2022-04-23 11:53 UTC, tsmethurst commented on docs/installation_guide/nginx.md
> +Or if you don't have a systemd service just stop it manually.
Hmm, I guess telling them how to stop it is out of scope here if we don't know how they started it :P What do you think?

2022-04-24 09:04 UTC, merged