fix existing bio text showing as HTML
superseriousbusiness/gotosocial pull request #531
Opened 2022-05-02 14:50 UTC by NyaaaWhatsUpDoc

- updated replaced mentions to include instance
- strips HTML from account source note in Verify handler
- update text formatter to use buffers for string writes

2022-05-02 17:24 UTC, igalic requested changes
some regex nonsense spotted

2022-05-02 17:24 UTC, igalic commented on internal/regexes/regexes.go
> +	schemes = `(((http|https))://)`
why are there so many capture groups in this regex?

2022-05-02 17:24 UTC, igalic commented on internal/regexes/regexes.go
> +	schemes = `(((http|https))://)`
this should be enough:
```suggestion
	schemes = `(http|https)://`
```

2022-05-02 17:28 UTC, NyaaaWhatsUpDoc commented on internal/regexes/regexes.go
> +	schemes = `(((http|https))://)`
this was literally just a drag and drop from another area of the code. you're right :sweat_smile:

2022-05-02 17:30 UTC, NyaaaWhatsUpDoc commented
This still needs a specific test writing for the AccountVerify method, and there's an existing replacementions test that needs fixing

2022-05-03 00:16 UTC, igalic commented
btw, is this https://github.com/superseriousbusiness/gotosocial-admin/issues/11 related?

2022-05-03 11:57 UTC, NyaaaWhatsUpDoc commented
> btw, is this [superseriousbusiness/gotosocial-admin#11](https://github.com/superseriousbusiness/gotosocial-admin/issues/11) related?

not directly i don't think, as the code with the logic mainly being changed here is the mentions code. but certainly an issue in a similar area of the codebase i'm sure

2022-05-05 07:24 UTC, NyaaaWhatsUpDoc commented
Todo:
- update internal/processing/status tests
- update internal/api/client/accountverify test to also check for a plaintext note in Account.Source

2022-05-07 15:54 UTC, tsmethurst approved these changes

2022-05-07 15:55 UTC, merged