[feature] Media cleanup endpoint
superseriousbusiness/gotosocial pull request #560
Opened 2022-05-13 11:08 UTC by zethra

Adds an admin endpoint to trigger a remote media cleanup.

Fixed #348

2022-05-13 11:26 UTC, tsmethurst requested changes
Almost there, just a few swagger things

2022-05-13 11:26 UTC, tsmethurst commented on internal/api/client/admin/mediacleanup.go
> +// consumes:
Since it can also consume json or xml, this should be:

```
// consumes:
// - application/json
// - application/xml
// - application/x-www-form-urlencoded
```

2022-05-13 11:26 UTC, tsmethurst commented on internal/api/model/admin.go
> +type MediaCleanupRequest struct {
You should annotate this as pertaining to a specific request endpoint, like we do here: https://github.com/superseriousbusiness/gotosocial/blob/898d256511fdddbc6b5e783116b07fd240b28819/internal/api/model/account.go#L95-L97

In this case, the annotation should be:

```
// MediaCleanupRequest models admin media cleanup parameters
//
// swagger:parameters mediaCleanup
```

2022-05-13 11:26 UTC, tsmethurst commented on internal/api/model/admin.go
> +	RemoteCacheDays string `form:"remote_cache_days" json:"remote_cache_days" xml:"remote_cache_days"`
You can make this an int :)

2022-05-13 11:26 UTC, tsmethurst commented on internal/api/client/admin/mediacleanup.go
> +// parameters:
If you annotate the struct consumed by this endpoint (see below) you can delete this 'parameters' section

2022-05-13 11:32 UTC, zethra commented on internal/api/model/admin.go
> +	RemoteCacheDays string `form:"remote_cache_days" json:"remote_cache_days" xml:"remote_cache_days"`
Go question. If I do make this an int and no value or an empty value is provided, will parsing produce and error or a zero value?

2022-05-13 12:21 UTC, tsmethurst commented on internal/api/model/admin.go
> +	RemoteCacheDays string `form:"remote_cache_days" json:"remote_cache_days" xml:"remote_cache_days"`
good question; I think it will only fail if you have the 'required' annotation in the struct tags, so you should be OK and empty values will just parse as the zero value for an int (which is zero); if they provide no value, or zero, better take whatever the admin has set as their media-remote-cache-days config value (you can get this with `viper.GetInt(config.Keys.MediaRemoteCacheDays)`

2022-05-13 12:29 UTC, igalic commented on internal/api/model/admin.go
> +	RemoteCacheDays string `form:"remote_cache_days" json:"remote_cache_days" xml:"remote_cache_days"`
in general, in go, ***everything*** is zero initialised, unless you tell it to do otherwise

sometimes this isn't useful or sensible, but it's marginally better than having leftover garbage (or for security… researchers: treasure) in a new variable.

2022-05-13 12:31 UTC, zethra commented on internal/api/model/admin.go
> +	RemoteCacheDays string `form:"remote_cache_days" json:"remote_cache_days" xml:"remote_cache_days"`
That would mean it's impossible to request clearing all remote media by explicitly requesting 0 days. This is acceptable?

2022-05-13 12:34 UTC, igalic commented on internal/api/model/admin.go
> +	RemoteCacheDays string `form:"remote_cache_days" json:"remote_cache_days" xml:"remote_cache_days"`
you could have -1 be that magic number
or you could set a different default in the "constructor"

2022-05-13 12:36 UTC, tsmethurst commented on internal/api/model/admin.go
> +	RemoteCacheDays string `form:"remote_cache_days" json:"remote_cache_days" xml:"remote_cache_days"`
Yeah I'd also say -1 can mean 'clear everything', that seems OK

2022-05-13 12:36 UTC, zethra commented on internal/api/model/admin.go
> +	RemoteCacheDays string `form:"remote_cache_days" json:"remote_cache_days" xml:"remote_cache_days"`
This is why I used a string. I can differentiate between no value given and 0/

2022-05-13 12:38 UTC, zethra commented on internal/api/model/admin.go
> +	RemoteCacheDays string `form:"remote_cache_days" json:"remote_cache_days" xml:"remote_cache_days"`
Making -1 clear everything and 0 use the default time is unintuitive. Having 0 clear everything and having no value use the default time makes much more sense.

2022-05-13 12:39 UTC, tsmethurst commented on internal/api/model/admin.go
> +	RemoteCacheDays string `form:"remote_cache_days" json:"remote_cache_days" xml:"remote_cache_days"`
i think it's OK if the api is like:

- a positive number: uncache media older than this number
- `0` or not set: uncache media according to the setting `media-remote-cache-days`
- `-1` or less: uncache everything

2022-05-13 12:40 UTC, zethra commented on internal/api/model/admin.go
> +	RemoteCacheDays string `form:"remote_cache_days" json:"remote_cache_days" xml:"remote_cache_days"`
Alright, if that's you decision. But I personally dislike that design.

2022-05-13 12:45 UTC, tsmethurst commented on internal/api/model/admin.go
> +	RemoteCacheDays string `form:"remote_cache_days" json:"remote_cache_days" xml:"remote_cache_days"`
Hmm okay thinking about it more maybe it makes sense to use an int pointer here then, and if it's nil take the default, and if it's zero or negative, clear everything

2022-05-13 13:34 UTC, tsmethurst commented on internal/api/client/admin/mediacleanup.go
> +	err = m.processor.AdminMediaRemotePrune(c.Request.Context(), remoteCacheDays)
Forgot to mention earlier, this function returns a gtserror which should have a code and a message built in, so you can do:

```
if errWithCode := m.processor.AdminMediaRemotePrune(c.Request.Context(), remoteCacheDays); errWithCode != nil {
  		l.Debugf("error starting prune of remote media: %s", errWithCode.Error())
		c.JSON(errWithCode.Code(), gin.H{"error": errWithCode.Safe()})
		return
}

```

We do something similar here: https://github.com/superseriousbusiness/gotosocial/blob/9f2a2abe42a6211df6970ba7625d245298778a38/internal/api/client/status/statusboost.go#L69-L104

Eventually we will refactor all the processor functions that are called by the API packages to return this kind of error, so might as well do this now to save time later :)

2022-05-13 23:53 UTC, igalic commented on internal/api/model/admin.go
> +	RemoteCacheDays string `form:"remote_cache_days" json:"remote_cache_days" xml:"remote_cache_days"`
@zethra what would your string based API have been?

2022-05-14 09:20 UTC, tsmethurst commented
This looks great :) Do you feel like also writing a small test suite for this, in the style of the other test suites in the admin package? No worries if not, I'm happy to merge as-is and write a test myself later, just thought I'd check :)

2022-05-14 09:25 UTC, zethra commented
I can take a crack it. Though due to the timezone difference I probably won't get to it until tomorrow for you.

2022-05-15 12:39 UTC, zethra commented
Fixed the formattting

2022-05-15 12:48 UTC, tsmethurst reviewed
Looks great now! Good job on the tests. If you can just add the license text to that one file and then i will merge this :)

2022-05-15 12:48 UTC, tsmethurst commented on internal/api/client/admin/mediacleanup_test.go
> +package admin_test
can you add the license comment in here?

2022-05-15 12:48 UTC, zethra commented on internal/api/client/admin/mediacleanup_test.go
> +package admin_test
Sure

2022-05-15 12:51 UTC, tsmethurst approved these changes

2022-05-15 12:52 UTC, merged