implement custom_emojis endpoint
superseriousbusiness/gotosocial pull request #563
Opened 2022-05-13 14:51 UTC by i-am-a-paull

This is a stab at implementing /api/v1/custom_emojis. I made some guesses about where things went, so if they need to go elsewhere I can move them when I get the chance. I'm also not completely satisfied with the tests but I can get around to improving those too at some point :sweat_smile:

2022-05-13 15:31 UTC, NyaaaWhatsUpDoc commented on internal/processing/media/getemoji.go
> +	apiEmojis := []*apimodel.Emoji{}
Since you already know the number of DB emoji entries you can initialize this with `make([]*apimodel.Emoji, 0, len(emojis))` which for a very large slice will be more performant :)

2022-05-13 22:51 UTC, i-am-a-paull commented on internal/processing/media/getemoji.go
> +	apiEmojis := []*apimodel.Emoji{}
Ooh thanks!

2022-05-14 09:31 UTC, tsmethurst commented on internal/processing/media/getemoji.go
> +			logrus.Errorf("error converting emoji with id %s: %s", gtsEmoji.ID, err)
if you error here you should `continue` after logging it so you don't risk putting a malformed emoji struct in the apiEmojis slice

2022-05-14 09:32 UTC, tsmethurst requested changes
Looks brilliant to me, just one small fix and then I think this can be merged :) Great job

2022-05-20 01:03 UTC, i-am-a-paull commented on internal/processing/media/getemoji.go
> +			logrus.Errorf("error converting emoji with id %s: %s", gtsEmoji.ID, err)
thanks! I've been mostly afk for a few days but I finally got it in :sweat_smile:

2022-05-20 08:34 UTC, tsmethurst approved these changes

2022-05-20 08:34 UTC, merged