Allow user to show instead of landing page on /
superseriousbusiness/gotosocial pull request #922
Opened 2022-10-25 05:43 UTC by i5heu

2022-10-25 08:34 UTC, tsmethurst requested changes
Cool PR :)

You'll have to fiddle with `test/cliparsing.sh` and `test/envparsing.sh` to get it passing tests. Basically you just gotta add the new parameters to the expected output there. Let me know if you need any help with it :)

2022-10-25 08:34 UTC, tsmethurst commented on internal/web/profile.go
> +	config.Config(func(cfg *config.Configuration) {
I think you can do this a bit more simply:

```go
var username string
if landingPageUser := config.GetLandingPageUser(); landingPageUser != "" {
  username = landingPageUser
} else {
  username = strings.ToLower(c.Param(usernameKey))
}
```

2022-10-25 08:34 UTC, tsmethurst commented on internal/web/web.go
> +	config.Config(func(cfg *config.Configuration) {
you can simplify this one too, using something similar to what i wrote above :)

2022-10-29 15:13 UTC, tsmethurst commented on internal/web/web.go
> +	if landingPageUser := config.GetLandingPageUser(); landingPageUser == "" {
Rather than serving a whole different handler here if `config.GetLandingPageUser()` is set, I would rather we do a 302 redirect to the set profile from within the baseHandler. Could you make that change? Then I think this will be good to merge :)

2022-10-29 15:13 UTC, tsmethurst commented
Heya, sorry for responding slowly again. I'm only just getting back to GtS properly now after time away and then being ill. I added just one more review comment :) After that this should be good to go

2022-10-29 18:12 UTC, i5heu commented on internal/web/web.go
> +	if landingPageUser := config.GetLandingPageUser(); landingPageUser == "" {
Ya this is a better way to do that :3

2022-10-30 09:36 UTC, NyaaaWhatsUpDoc commented on internal/web/profile.go
> +	if landingPageUser := config.GetLandingPageUser(); landingPageUser != "" {
Will this code not always return the landing page user for any profile GET request? surely we can just leave this to the logic it was previously since we now have the redirect in place now? :thinking:

2022-10-30 09:38 UTC, i5heu commented on internal/web/profile.go
> +	if landingPageUser := config.GetLandingPageUser(); landingPageUser != "" {
true!
i change this in a minute ^^

2022-10-30 13:15 UTC, tsmethurst commented on internal/web/web.go
> +	} else {
rather than doing this if/else here, i would just serve m.baseHandler as before, but put the redirect logic right at the top of that function instead, and return early with the redirect if landingPageUser is set

this means that in the future if we have some way of changing landingPageUser while the instance is still running (hotloading config) then the instance won't need to be restarted to make it work :)

2022-10-30 13:15 UTC, tsmethurst commented on internal/web/profile.go
> +	c.Redirect(http.StatusMovedPermanently, "/@"+c.Param(strings.ToLower(landingPageUser)))
I would make this a 302 rather than 301 -- we don't want browsers to cache the redirect, in case the setting changes at some point

2022-11-03 12:15 UTC, tsmethurst commented
Looks good now! Thank you for this, and for making the changes :)

2022-11-03 12:15 UTC, merged