[feature] Allow newly uploaded emojis to be placed in categories
superseriousbusiness/gotosocial pull request #939
Opened 2022-11-01 11:04 UTC by tsmethurst

- Added database model for emoji categories.
- Updated select for emojis to also select emoji category.
- Serialize emoji category properly to the frontend.
- Added endpoint `GET /api/v1/admin/custom_emojis/categories` to list all existing emoji categories.
- Added `category` to emoji upload. Emoji will be put in given category. If given `category` doesn't yet exist, it will be created.
- Limit category name to 64 characters (arbitrary number, should be long enough I think)

2022-11-01 13:58 UTC, f0x52 requested changes

2022-11-01 13:58 UTC, f0x52 commented on docs/api/swagger.yaml
> +                - description: Category in which to place the new emoji. 64 characters or less. If left blank, emoji will be uncategorized, but this can be updated later.
minor change here, but as we don't currently have the api routes to change them later, maybe note that?

2022-11-01 14:30 UTC, tsmethurst commented on docs/api/swagger.yaml
> +                - description: Category in which to place the new emoji. 64 characters or less. If left blank, emoji will be uncategorized, but this can be updated later.
Done! :) https://github.com/superseriousbusiness/gotosocial/pull/939/commits/eb72766e6f8666fe99ba670f514ee06b48d0ae52

2022-11-14 22:46 UTC, NyaaaWhatsUpDoc commented
Looks good to me :)

2022-11-14 22:47 UTC, merged